name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install libraries
        run: | 
          sudo apt-get update
          sudo apt-get install build-essential gcc gdb valgrind

      - name: Build & install Criterion
        run: |
          git clone --recursive https://github.com/Snaipe/Criterion && cd Criterion/
          meson build && ninja -C build
          sudo ninja -C build install
      
      - name: Build project
        run: make all