name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install libraries
        run: | 
          sudo apt-get update
          sudo apt-get install build-essential gcc gdb valgrind criterion-dev
      
      - name: Build project
        run: make all